; PlatformIO Project Configuration File
; RobotDyn WiFi D1 R2 = ESP8266-based, same as Wemos D1 R2

[env:d1_r2]
platform = espressif8266
board = d1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
upload_speed = 115200

lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    bblanchon/ArduinoJson@^7.0.0